local env = env
GLOBAL.setfenv(1, GLOBAL) -- Moves us from modding env to global env, keeping the mod env handy in case we need it.

-- lable
STRINGS.NAMES.TAB_LABEL = "模组合集"
STRINGS.NAMES.TAB_LABEL_DESC = "批量启用MOD，轻松切换游戏风格"

-- button
STRINGS.NAMES.CREATE_PACK_BUTTON = "创建一个新mod合集"
STRINGS.NAMES.VIEW_PACK_BUTTON = "查看mod合集"
STRINGS.NAMES.UPDATE_PACK_BUTTON = "修改mod合集"
STRINGS.NAMES.DELETE_PACK_BUTTON = "删除mod合集"
STRINGS.NAMES.UPDATE_IMAGE_BUTTON = "更新图片"

-- warning
STRINGS.NAMES.NO_MODS_WARING = "这个合集中没有mod"
STRINGS.NAMES.NO_MODS_CONTENT_WARING = "你还没有mod合集，点击下面的加号去创建一个"
STRINGS.NAMES.NO_MODS_ENABLE_WARING = "这个合集中没有mod被启用"
STRINGS.NAMES.SOME_MODS_ENABLE_WARING = "这个合集中的一些mod被启用"
STRINGS.NAMES.ALL_MODS_ENABLE_WARING = "这个合集中所有的mod都被启用"

-- confrim 
STRINGS.NAMES.DISABLE_MOD_PACK = "启用合集"
STRINGS.NAMES.DISABLE_MOD_PACK_CONTENT = "这将禁用这个合集外的的所有mod"
STRINGS.NAMES.DELETE_MOD_PACK = "删除合集"
STRINGS.NAMES.DELETEE_MOD_PACK_CONTENT = "删除此合集将永久删除它，并且无法撤消！"
STRINGS.NAMES.UPDATE_MOD_PACK = "更新合集"
STRINGS.NAMES.UPDATE_MOD_PACK_CONTENT = "更新合集中的mod，当mod有修改时，请手动更新，并且无法恢复！"
STRINGS.NAMES.CONFRIM_BUTTON = "确认"
STRINGS.NAMES.UPDATE_PACK_IMAGE_TITLE = "请选择图片"

-- window
STRINGS.NAMES.CREATE_PACK_WINDOW_TITLE = "创建一个新mod合集"
STRINGS.NAMES.CREATE_PACK_MISS_NAME_WINDOW_TITLE = "合集无名称"
STRINGS.NAMES.CREATE_PACK_MISS_NAME_WINDOW_CONTENT = "请输入合集名称"
STRINGS.NAMES.CREATE_PACK_REPEAT_NAME_WINDOW_TITLE = "名称重复"
STRINGS.NAMES.CREATE_PACK_REPEAT_NAME_WINDOW_CONTENT = "已经有一个合集叫做这个名字，请换一个名字"